import { BASE, launch } from './helpers.mjs';
const b = await launch();
const p = await (await b.newContext({ viewport:{width:1280,height:800}, locale:'ko-KR' })).newPage();
let f=0; const ok=(c,m)=>{if(!c)f++;console.log(c?'ok  ':'FAIL',m)};
await p.goto(BASE + ''); await p.waitForSelector('.mode-card');
ok(await p.locator('.mode-card').count()===3,'3 mode cards on home');
await p.locator('.mode-card').nth(2).click();
await p.waitForSelector('.form-grid');
ok(location=>true,'form open'); ok((await p.textContent('h1, h2')).includes('편한 신발'),'title');
await p.getByRole('button',{name:'5시간 이상'}).click();
await p.getByRole('button',{name:'발바닥 · 뒤꿈치'}).click();
await p.getByRole('button',{name:'무릎'}).click();
const req = p.waitForRequest(r=>r.url().includes('/recommend/comfort'));
await p.getByRole('button',{name:'추천 받기'}).click();
const body = JSON.parse((await req).postData());
console.log(JSON.stringify(body));
ok(body.hours==='5시간 이상' && body.pain.length===2 && !body.pain.includes('없음'),'payload');
await p.waitForSelector('.card');
ok(await p.locator('.card').count()>0,'results shown');
await p.getByRole('button',{name:'뒤로'}).first().click().catch(()=>{});
await p.goto(BASE + '#/search'); await p.waitForSelector('.mode-card');
ok(await p.locator('.mode-card').count()===3,'3 cards on search');
await b.close(); process.exit(f?1:0);
